### ISSUE TITLE
About Yaml file

### ISSUE THREAD

**Issue by lavakush07** [ashutosh1919/kubernetes-deploy-tutorial#1]
I am not able to add multiple files into the deployment.yaml It is showing errors to me

**Comment by ashutosh1919** [comment]
There should be only single yaml file for kubernetes deployment. You could have multiple services in single deployment.

**Comment by lavakush07** [comment]
Okay, Yesterday I have seen your  youtube video in that u have  assigned two files in single deployment.

**Comment by ashutosh1919** [comment]
I think you are confused. In that video, one is `.yml` file and another is `.yaml` file
